### ISSUE TITLE
Followed Maps Not Showing Up

### ISSUE THREAD

**Issue by sethburtonhall** [ushahidi/crowdmap-issues#223] opened 2013-05-31 15:32 UTC
I followed a new map

https://crowdmap.com/user/whiteafrican

but when I go to my maps/followed only mine and another shows up - http://cl.ly/PLUm

**Comment by brianherbert** [comment] 2013-06-01 05:44
Hey Seth, this is actually related to my comment here: https://github.com/ushahidi/crowdmap-issues/issues/217#issuecomment-18656651

User profiles aren't "maps" but they are displayed a lot like them. We will need to consider this when doing map discoverability when we chat on Monday.

**Comment by brianherbert** [comment] 2013-06-01 05:45
Closing since this is currently expected behavior.

**Closed as completed by brianherbert** 2013-06-01 05:45 UTC

**Comment by sethburtonhall** [comment] 2013-06-01 16:20
Oh, ok, makes sense. I thought it was a map of Erik's travel.
