### ISSUE TITLE
Commenting Bug

### ISSUE THREAD

**Issue by sethburtonhall** [ushahidi/crowdmap-issues#239] opened 2013-06-10 12:44 UTC
When I clicked "Share Comment" the comment posted but the text field remained occupied. I thought it didn't post so I clicked "Share Comment" again and ... Double Post.

http://cl.ly/PWIR

**Comment by brianherbert** [comment] 2013-06-10 12:50
Duplicate of #237 
Thanks ;)

**Closed as completed by brianherbert** 2013-06-10 12:50 UTC
