### ISSUE TITLE
Facebook + Post sharing = love

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/crowdmap-issues#261] opened 2013-06-14 16:13 UTC
Make it possible for individual crowdmap posts to show photos and content on Facebook. 

Ushahidi page:
https://www.facebook.com/ushahidi?fref=ts

What you see: 
http://dl.dropbox.com/u/34693557/Screenshots/fj.png

It would be better for community/interaction to be able to post the individual maps/posts and the associated rich media content

**Comment by brianherbert** [comment] 2013-06-15 01:10
Duplicate of #164 

I think this may be related to an issue I'm having with #258 not working on production, also.

Closing.

**Closed as completed by brianherbert** 2013-06-15 01:10 UTC
Labels: bug
