### ISSUE TITLE
Viewing notificiations

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/crowdmap-issues#222] opened 2013-05-31 15:10 UTC
Viewing one notification renders all notifications as 'read'. 

Steps:
1. View inbox - http://dl.dropbox.com/u/34693557/Screenshots/ew.png
2. click on first message to view and action
3. Return to inbox. All other notifications gone. Unable to track back
4. http://dl.dropbox.com/u/34693557/Screenshots/ey.png

Bonus points - Feature - be able to view notifications for day or week?

**Comment by evansims** [comment] 2013-05-31 23:46
Hey Heather,

Thanks for bringing this up. So this behavior is actually by design. I originally had it setup so that notifications had to be clicked through to mark as read, but we ended up feeling like this required a bit too much micromanagement to deal with when things got busy. We didn't want notifications to feel like an inbox, as you already get enough of that experience elsewhere.

Instead we adopted to a Google+ style approach in that the notification counter is dismissed once the inbox is opened. This means that all unread messages get marked as read once the inbox is opened, as Google+ does.

We don't have a delete option on notifications, and instead automatically expire notifications after a predefined amount of time, as Facebook does. Read emails expire after two weeks and unreads expire after two month, I think. You're also capped at 50 notifications, before the oldest ones start dropping off the list.

I agree this inbox concept could use refinement; just trying to share the logic behind the current behavior and to affirm this isn't a bug.

I'd like to bring additional thinking caps in on this; let's open a Basecamp thread so we can get the designer/biz folk in on it too.

**Comment by heatherleson** [comment] 2013-06-03 21:18
moved to basecamp

**Comment by heatherleson** [comment] 2013-06-05 19:01
I prefer the example from our wiki on how to display and review notifications - http://dl.dropbox.com/u/34693557/Screenshots/fa.png

**Comment by evansims** [comment] 2014-03-30 22:15
Notifications are receiving some updates in the forthcoming UI update that make this more logical. New notifications are marked as unread, naturally. These are highlighted in the UI with a special hue. Clicking through a notification to view the relating URL will mark the notification as read.

**Closed as completed by evansims** 2014-03-30 22:15 UTC
Labels: enhancement, question
