### ISSUE TITLE
Location search in areas with many pins

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/crowdmap-issues#228] opened 2013-06-05 20:00 UTC
I noticed that adding locations in NYC is hard. It pulls up a large 'suggested' menu of NYC locations when all i want to do is add the general city.

steps:
1. add location NYC
2. click search
3. retrieve massive 4square list
4. Try to select 'nyc', the list lags (on wifi or on roaming - not the issue)
5. see 
![location search spinning](https://f.cloud.github.com/assets/1216707/614305/7caa7be0-ce1a-11e2-95e9-c34adb8d0100.png)

In order to add the location, I have to try to force "new york". It won't let me scroll to the bottom to click "done". 

Would it not be better, easier to allow people to add the main city before offering up all the potential 'sub-location' pins.

**Comment by brianherbert** [comment] 2013-06-06 01:35
It should auto select the generic region name, also depending on zoom level. Basically, if you search New York, it should auto select new york at the top of the list. When you click your selection, you don't need to hit done, the window should go back to the post message automatically.

This looking like an Android specific bug.

**Comment by evansims** [comment] 2013-07-31 20:09
I'm not able to reproduce this issue on Android 4.2.2

**Comment by evansims** [comment] 2014-03-30 22:12
This workflow gotten a lot of love in the forthcoming UI update, so going to close this bug. Thanks!

**Closed as completed by evansims** 2014-03-30 22:12 UTC
Labels: bug, android
