### ISSUE TITLE
Better uploading indicator on map settings

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#135] opened 2013-05-06 05:45 UTC
We have two image upload fields in map settings. We need to have a better upload experience. Currently it just fades out the current image and fades in the new one that you upload but the indicator that something is uploading is unclear.

![screen shot 2013-05-06 at 2 43 43 pm](https://f.cloud.github.com/assets/106068/464820/0fa095e2-b610-11e2-9b26-d9b407201f3f.png)

**Comment by evansims** [comment] 2014-03-30 22:17
Dupe of ushahidi/crowdmap-issues#235

**Closed as completed by evansims** 2014-03-30 22:17 UTC
Labels: enhancement
