### ISSUE TITLE
Community Engagement Setting

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/crowdmap-issues#199] opened 2013-05-23 10:04 UTC
I have an existing account, so there is no way for me to test selecting "newsletter signup". 

For users, provide an account settings as an opt in for crowdmap communications. This can help current classic users or people who skip this option during sign up. If it is in the settings to auto-opt in for communications, this could push to campaign monitor. 

By doing this, it removes the need to ask for a db list from a developer. It puts the communications in the hands of the crowdmap user and the communications staffer.

**Comment by brianherbert** [comment] 2013-05-23 13:31
This is a duplicate of #193. Closing.

All users are already on the email list before the checkbox went on the signup form. They can unsubscribe from the email if they choose to since subscriptions are handled by Campaign Monitor. We did this with Classic previously.

It's impossible to skip during signup.

**Closed as completed** 2013-05-23 13:32 UTC
Labels: enhancement
