### ISSUE TITLE
Posts owned by a map should be editable by map collaborators

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#298] opened 2013-07-23 06:45 UTC
Posts that are owned by a map (where owner_map_id is set) should be editable by any of the collaborators on that map.

Keep in mind all posts are still technically owned by the user who originally posted it, or the anonymous user.

**Comment by evansims** [comment] 2014-03-30 22:32
Dupe of ushahidi/crowdmap-issues#39

**Closed as completed by evansims** 2014-03-30 22:32 UTC
Labels: enhancement
