### ISSUE TITLE
Comment stays in the comment box after its been posted

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/crowdmap-issues#244] opened 2013-06-11 01:44 UTC
I'd expect the comment box to be cleared after the post.

![screen shot 2013-06-11 at 1 43 18 pm](https://f.cloud.github.com/assets/7965/635103/5c11ed6a-d238-11e2-9120-51a8a3fd98d2.png)

**Comment by brianherbert** [comment] 2013-06-11 01:57
Duplicate of #237

**Closed as completed by brianherbert** 2013-06-11 01:57 UTC
Labels: bug
