### ISSUE TITLE
Viewing Inbox times out

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#130] opened 2013-05-05 08:26 UTC
When viewing the inbox (probably only with lots of notifications), I'm getting a 504 timeout.

Screenshot: 
http://cl.ly/image/0V0d2J360K0V

**Comment by evansims** [comment] 2013-05-05 21:40
Going to close this one as a dupe of #54 as the problem and solution will be the same. :)

**Closed as completed by evansims** 2013-05-05 21:40 UTC
Labels: bug

**Comment by brianherbert** [comment] 2013-05-05 23:57
I was looking for that ticket but I was on my phone. Thanks :)
