### ISSUE TITLE
Dropdown link not working

### ISSUE THREAD

**Issue by aoduor** [ushahidi/crowdmap-issues#256] opened 2013-06-13 05:07 UTC
:(

Trying to view my notifications from the top right hand corner of the page but it won't open. Firebug didn't tell me anything either :(

![screenshot](http://i.imgur.com/dtzhtik.png)

**Comment by evansims** [comment] 2013-06-16 06:05
Hm, I can't seem to reproduce this bug. Can you tell me what browser/version (assuming latest Firefox?) you're using, and does it happen all the time or on specific pages?

**Comment by evansims** [comment] 2013-06-19 18:37
Still can't reproduce this. Need more information @aoduor

**Comment by heatherleson** [comment] 2013-06-19 18:43
i closed the browser session. kept clicking and was eventually able to get in.

I confirm this issue
ff
multiple tabs open
action - logged in, click on dropdown menu 'cog'. Unable to get into the platform menu.

**Comment by evansims** [comment] 2013-06-19 18:50
Session wouldn't have anything to do with this, nor would multiple tabs. Are you able to reproduce the problem on a specific page, or was it happening on all pages?

**Comment by heatherleson** [comment] 2013-06-19 18:53
This was experienced Logged in via FF on the following pages: 
Crowdmap home page (global), 
Crowdmap (my followers, maps, posts etc)
Crowdmap My page (my posts)

**Comment by evansims** [comment] 2013-06-19 19:06
Hm. Only thing I can think of is that you guys are hitting a JS error somewhere that is breaking things. Hard thing to track down, but I'll keep an eye out.

**Comment by evansims** [comment] 2013-08-01 06:01
I still haven't been able to reproduce this bug, but there's been a lot of changes since it was filed. @aoduor @heatherleson Can you retry this and let me know if it's still happening for you?

**Comment by evansims** [comment] 2014-03-30 21:55
This workflow has been entirely reworked with the forthcoming UI update. Marking as obsolete.

**Closed as completed by evansims** 2014-03-30 21:55 UTC
Labels: bug
