### ISSUE TITLE
Edit, Add location = Freeze

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/crowdmap-issues#323] opened 2013-08-22 22:09 UTC
Attempted to add location to this post: http://dl.dropbox.com/u/34693557/Screenshots/h0.png

It froze and won't add the location. Tried both boxes, Tried reloading.

Browser FF.
location - Redmond. Washington
![h0](https://f.cloud.github.com/assets/1216707/1012822/883c92f0-0b77-11e3-8fe9-d46fcdc9bfd2.png)

**Comment by brianherbert** [comment] 2013-08-23 01:55
Duplicate of #318 

Firefox now blocks mixed content by default. OSM's geocoder does not support SSL so Firefox doesn't allow it to be loaded on a page that uses SSL.

Closing.

**Closed as completed by brianherbert** 2013-08-23 01:55 UTC
Labels: bug
